[FB_DEVICE]
FB_HWLAYER_ID = 1
FB_HWWIN_ID = 0
FB_HWLAYER_DST = 3
FB_HWWIN_FORMAT = 5
FB_HWLAYER_OUTPUTCOLOR = 0 
FB_WIDTH = 752
FB_HEIGHT = 560
FB_TIMMING_WIDTH = 752
FB_TIMMING_HEIGHT = 560
FB_MMAP_NAME = E_MMAP_ID_FB
FB_BUFFER_LEN = 6144
#unit:Kbyte,6144=6M, fbdev.ko alloc size = FB_BUFFER_LEN*1024
