#!/bin/sh

# This file is part of PulseAudio.
#
# Copyright 2006 Lennart Poettering
# Copyright 2006 Pierre Ossman <ossman@cendio.se> for Cendio AB
#
# PulseAudio is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# PulseAudio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with PulseAudio; if not, see <http://www.gnu.org/licenses/>.

while getopts 'hs:n:m:MSDd' param ; do
	case $param in
		d)
			if [ x"$PADSP_DEBUG" = x ]; then
				PADSP_DEBUG=1
			else
				PADSP_DEBUG=$(( $PADSP_DEBUG + 1 ))
			fi
			export PADSP_DEBUG
			;;
		*)
			echo "$0 - redirect OSS audio devices to PulseAudio"
			echo " "
			echo "$0 [options] application [arguments]"
			echo " "
			echo "options:"
			echo "	-h                  show brief help"
			echo "	-d                  enable debug output"
			exit 0
			;;
	esac
done

shift $(( $OPTIND - 1 ))

if [ x"$LD_PRELOAD" = x ] ; then
   LD_PRELOAD="/mnt/SDCARD/audiotest/libpadsp.so"
else
   LD_PRELOAD="$LD_PRELOAD /mnt/SDCARD/audiotest/libpadsp.so"
fi

export LD_PRELOAD

exec "$@"
